apiVersion: v1
kind: Service
metadata:
  name: ravp-platform-ui
  namespace: ravp
  labels:
    app: ravp-platform-ui
  annotations:
    cloud.google.com/backend-config: '{"default": "ravp-platform-ui-backendconfig"}'
spec:
  type: ClusterIP
  ports:
    - port: 8501
      targetPort: 8501
      protocol: TCP
      name: http
  selector:
    app: ravp-platform-ui
