apiVersion: v1
kind: Service
metadata:
  name: ravp-control-plane
  namespace: ravp
  labels:
    app: ravp-control-plane
spec:
  type: ClusterIP
  ports:
    - port: 8010
      targetPort: 8010
      protocol: TCP
      name: http
  selector:
    app: ravp-control-plane
