versions:
- version: 1.0.0
  previous_version: null
  timestamp: '2026-02-07T15:10:58Z'
  changed_by: admin
  changes:
    initial:
    - Initial version
- version: 2.0.0
  previous_version: 1.0.0
  timestamp: '2026-02-07T18:28:11Z'
  changed_by: admin
  changes:
    major:
    - requires_human_approval changed
    minor:
    - 'pii_level: medium -> high'
    patch: []
